model:
  name: "MobileNetV3_UnfrozenLN"
  backbone: MobileNetV3Large
  input_shape: [224, 224, 3]
  freeze_backbone: false

  custom_head:
    layers:
      - type: GlobalAveragePooling2D
      - type: LayerNormalization
      - type: Dense
        units: 256
        activation: relu
      - type: Dropout
        rate: 0.3
      - type: Dense
        units: 128
        activation: relu
      - type: Dense
        units: num_classes
        activation: softmax

training:
  optimizer: adam
  learning_rate: 0.00005  # Lower due to unfrozen base
  loss:
    type: categorical_crossentropy
    label_smoothing: 0.1
