model:
  name: "MobileNetV2_Frozen"
  backbone: MobileNetV2
  input_shape: [224, 224, 3]
  freeze_backbone: true

  custom_head:
    layers:
      - type: GlobalAveragePooling2D
      - type: BatchNormalization
      - type: Dropout
        rate: 0.4
      - type: Dense
        units: 256
        activation: relu
      - type: BatchNormalization
      - type: Dropout
        rate: 0.3
      - type: Dense
        units: num_classes
        activation: softmax

training:
  optimizer: adam
  learning_rate: 0.0001
  loss:
    type: categorical_crossentropy
    label_smoothing: 0.1
