collapse_labels: true

remap:
  PB_Downtrend: Uptrend
  CT_Uptrend: Uptrend
  PB_Uptrend: Downtrend
  CT_Downtrend: Downtrend
  Downtrend_Convergence: Downtrend
  Downtrend_No_Convergence: Downtrend
  Uptrend_Convergence: Uptrend
  Uptrend_No_Convergence: Uptrend
  Trend_Change_Bull: Trend_Change_Bull
  Trend_Change_Bear: Trend_Change_Bear
  No_Pattern: No_Pattern

vertical_flip_map:
  Uptrend: Downtrend
  Downtrend: Uptrend
  Trend_Change_Bull: Trend_Change_Bear
  Trend_Change_Bear: Trend_Change_Bull