# ⚙️ Training configuration for Convolution CV
debug: true

# Where raw images were staged (used to infer label set or for debug)
staging_dir: ./artifacts/staging

# Whether to preserve raw copy to artifacts/data/raw/
preserve_raw: yes

# Labeling strategy: 'pattern_only' or 'instrument_specific'
label_mode: pattern_only

# Train/val/test split ratios
split_ratios: [80, 10, 10]

# Random seed for reproducibility
random_seed: 1337

# Image size for resizing input data
image_size: [224, 224]

# Batch size for training and validation
batch_size: 32

# Number of training epochs
epochs: 50

# Cache dataset(s) in memory
cache: yes

# configs/callbacks.yaml

early_stopping:
  enabled: true
  monitor: val_loss
  patience: 10
  restore_best_weights: true
  verbose: 1
  mode: min

lr_scheduler:
  enabled: true
  monitor: val_loss
  factor: 0.5
  patience: 10
  min_lr: 1e-6
  verbose: 1
  mode: min

model_checkpoint:
  enabled: true
  filepath: best_model.keras   
  monitor: val_loss
  save_best_only: true
  save_weights_only: false
  verbose: 1
  mode: min